// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzeekoxgykzjzjprrmnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6ZWVrb3hneWt6anpqcHJybW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODk4MzAsImV4cCI6MjA3MDM2NTgzMH0.Vgq6rkX3ycJwFal9BFGXZWCLoi-SeEsgLTc5ygmG5qQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});